import { BrowserWindow, nativeImage, screen, Tray } from 'electron'
import { join } from 'node:path'
import type { UsageSnapshot } from '../shared/usage'
import { CLAUDE_ICON_PNG, CODEX_ICON_PNG } from '../shared/provider-icons'

const USAGE_WINDOW = { width: 356, height: 620 }
function trayImage(provider: 'codex' | 'claude'): Electron.NativeImage { const png = provider === 'codex' ? CODEX_ICON_PNG : CLAUDE_ICON_PNG; const image = nativeImage.createFromBuffer(Buffer.from(png, 'base64')).resize({ width: 18, height: 18 }); image.setTemplateImage(process.platform === 'darwin'); return image }
export interface UsageTrayController { show(snapshot: UsageSnapshot): void; hide(): void; toggle(snapshot: UsageSnapshot): void; updateTray(snapshot: UsageSnapshot): void; setBucket(id: string): void; destroy(): void }
export function createUsageTrayController(tray: Tray, loadRenderer: (window: BrowserWindow, hash?: string) => void, onClose: () => void, onContextMenu: (tray: Tray) => void, onOpen: () => void): UsageTrayController {
  let window: BrowserWindow | null = null; let latest: UsageSnapshot | null = null; let selectedBucketId = ''; let activeTray = tray
  const claudeTray = new Tray(trayImage('claude')); tray.setImage(trayImage('codex')); tray.setToolTip('Codex 사용량'); claudeTray.setToolTip('Claude 사용량')
  const ensureWindow = (): BrowserWindow => { if (window && !window.isDestroyed()) return window; window = new BrowserWindow({ ...USAGE_WINDOW, show: false, frame: false, resizable: false, minimizable: false, maximizable: false, fullscreenable: false, skipTaskbar: true, alwaysOnTop: true, backgroundColor: '#00000000', webPreferences: { preload: join(__dirname, '../preload/index.cjs'), contextIsolation: true, nodeIntegration: false, sandbox: true } }); window.setAlwaysOnTop(true, 'pop-up-menu'); window.on('blur', () => { if (window && !window.isDestroyed()) window.hide() }); window.on('closed', () => { window = null }); window.webContents.on('did-finish-load', () => { if (latest) window?.webContents.send('usage:snapshot', latest) }); loadRenderer(window, 'usage'); return window }
  const position = (target: BrowserWindow): void => { const bounds = activeTray.getBounds(); const area = screen.getDisplayMatching(bounds).workArea; const height = Math.min(USAGE_WINDOW.height, area.height); const x = Math.min(Math.max(Math.round(bounds.x + bounds.width / 2 - USAGE_WINDOW.width / 2), area.x), area.x + area.width - USAGE_WINDOW.width); const y = process.platform === 'darwin' ? area.y : Math.min(bounds.y + bounds.height + 6, area.y + area.height - height); target.setSize(USAGE_WINDOW.width, height, false); target.setPosition(x, y, false) }
  const emptySnapshot = (): UsageSnapshot => ({ codex: { provider: 'codex', status: 'loading', buckets: [], updatedAt: null }, claude: { provider: 'claude', status: 'loading', buckets: [], updatedAt: null } })
  const toggleFrom = (source: Tray): void => { activeTray = source; if (window?.isVisible()) { window.hide(); return }; const snapshot = latest ?? emptySnapshot(); latest = snapshot; onOpen(); const target = ensureWindow(); position(target); target.show(); target.focus(); target.webContents.send('usage:snapshot', snapshot) }
  tray.on('click', () => toggleFrom(tray)); claudeTray.on('click', () => toggleFrom(claudeTray)); tray.on('right-click', () => onContextMenu(tray)); claudeTray.on('right-click', () => onContextMenu(claudeTray))
  return { show(snapshot) { latest = snapshot; onOpen(); const target = ensureWindow(); position(target); target.show(); target.focus(); target.webContents.send('usage:snapshot', snapshot) }, hide() { if (window && !window.isDestroyed()) window.hide() }, toggle(snapshot) { if (window?.isVisible()) this.hide(); else this.show(snapshot) }, updateTray(snapshot) { latest = snapshot; const selected = snapshot.codex.buckets.find((bucket) => bucket.id === selectedBucketId) ?? snapshot.codex.buckets[0]; const codex = selected?.fiveHour; const claude = snapshot.claude.buckets[0]?.fiveHour; const label = (value: number | undefined) => value == null ? '—' : `${Math.round(value)}%`; tray.setImage(trayImage('codex')); claudeTray.setImage(trayImage('claude')); tray.setTitle(process.platform === 'darwin' ? `${label(codex?.usedPercent)}${selected?.weekly?.usedPercent === 100 ? ' !' : ''}${snapshot.codex.status === 'stale' ? ' ↻' : ''}` : 'CodeMung'); claudeTray.setTitle(process.platform === 'darwin' ? `${label(claude?.usedPercent)}${snapshot.claude.buckets[0]?.weekly?.usedPercent === 100 ? ' !' : ''}${snapshot.claude.status === 'stale' ? ' ↻' : ''}` : 'Claude'); if (window && !window.isDestroyed()) window.webContents.send('usage:snapshot', snapshot) }, setBucket(id) { if (typeof id === 'string' && id.length <= 120) { selectedBucketId = id; if (latest) this.updateTray(latest) } }, destroy() { onClose(); claudeTray.destroy(); if (window && !window.isDestroyed()) window.destroy(); window = null } }
}
